import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import AuthModal from "./components/auth/AuthModal";
import NavBar from "./components/nav/NavBar";
import { AuthProvider } from "@/providers/AuthProvider";
import AppShell from "./components/AppShell/AppShell";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ReduxProvider>
        <AuthProvider>
        <AuthModal/>
        <NavBar/>
        <AppShell>
           {children}
        </AppShell>
        </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
